package data.itemscustom

import character.Buff
import character.Stats
import data.Constants
import data.model.Item
import data.model.ItemSet
import data.model.Socket
import data.model.SocketBonus
import sim.SimParticipant
import kotlin.js.JsExport

@JsExport
class AtieshWarlock : Item() {
    override var isAutoGenerated: Boolean = false

    override var id: Int = 22630
    override var name: String = "Atiesh, Greatstaff of the Guardian (Warlock)"
    override var itemLevel: Int = 90
    override var quality: Int = 5
    override var icon: String = "inv_staff_medivh.jpg"
    override var itemSet: ItemSet? = null
    override var inventorySlot: Int = 17
    override var itemClass: Constants.ItemClass? = Constants.ItemClass.WEAPON
    override var itemSubclass: Constants.ItemSubclass? = Constants.ItemSubclass.STAFF
    override var allowableClasses: Array<Constants.AllowableClass>? = null
    override var minDmg: Double = 130.0
    override var maxDmg: Double = 243.0
    override var speed: Double = 2900.0
    override var stats: Stats = Stats(
        stamina = 30,
        intellect = 29,
        spellDamage = 150,
        spellCritRating = 28.0
    )
    override var sockets: Array<Socket> = arrayOf()
    override var socketBonus: SocketBonus? = null
    override var phase = 1

    val groupBuff = object : Buff() {
        override val name: String = "Power of the Guardian (Warlock)"
        override val icon: String = "inv_staff_medivh.jpg"
        override val durationMs: Int = -1
        override val hidden: Boolean = true

        override fun modifyStats(sp: SimParticipant): Stats {
            return Stats(spellDamage = 33)
        }
    }

    override var buffs: List<Buff> = listOf(groupBuff)
}
