package data.itemscustom

import character.*
import data.Constants
import data.model.Item
import data.model.ItemSet
import data.model.Socket
import data.model.SocketBonus
import kotlin.js.JsExport

@JsExport
class FistOfReckoning : Item() {
    override var isAutoGenerated: Boolean = false

    override var id: Int = 31139
    override var name: String = "Fist of Reckoning"
    override var itemLevel: Int = 88
    override var quality: Int = 3
    override var icon: String = "inv_mace_08.jpg"
    override var itemSet: ItemSet? = null
    override var inventorySlot: Int = 13
    override var itemClass: Constants.ItemClass? = Constants.ItemClass.WEAPON
    override var itemSubclass: Constants.ItemSubclass? = Constants.ItemSubclass.MACE_1H
    override var allowableClasses: Array<Constants.AllowableClass>? = null
    override var minDmg: Double = 102.0
    override var maxDmg: Double = 190.0
    override var speed: Double = 2700.0
    override var stats: Stats = Stats(
        physicalHitRating = 10.0,
        meleeCritRating = 16.0,
        rangedCritRating = 16.0,
        attackPower = 12,
        rangedAttackPower = 12
    )
    override var sockets: Array<Socket> = arrayOf()
    override var socketBonus: SocketBonus? = null
    override var phase = 1
}
