package data.itemscustom

import character.*
import data.Constants
import data.model.Item
import data.model.ItemSet
import data.model.Socket
import data.model.SocketBonus
import kotlin.js.JsExport

@JsExport
class GauntletsOfAnnihilation : Item() {
    override var isAutoGenerated: Boolean = false

    override var id: Int = 21581
    override var name: String = "Gauntlets of Annihilation"
    override var itemLevel: Int = 88
    override var quality: Int = 4
    override var icon: String = "inv_gauntlets_31.jpg"
    override var itemSet: ItemSet? = null
    override var inventorySlot: Int = 10
    override var itemClass: Constants.ItemClass? = Constants.ItemClass.ARMOR
    override var itemSubclass: Constants.ItemSubclass? = Constants.ItemSubclass.PLATE
    override var allowableClasses: Array<Constants.AllowableClass>? = null
    override var minDmg: Double = 0.0
    override var maxDmg: Double = 0.0
    override var speed: Double = 0.0
    override var stats: Stats = Stats(
        strength = 35,
        stamina = 15,
        meleeCritRating = 14.0,
        physicalHitRating = 10.0
    )
    override var sockets: Array<Socket> = arrayOf()
    override var socketBonus: SocketBonus? = null
    override var phase = 1
}
