package data.itemscustom

import data.Constants
import data.model.Item
import data.model.ItemSet
import data.model.Socket
import data.model.SocketBonus
import character.Stats
import kotlin.Array
import kotlin.Boolean
import kotlin.Double
import kotlin.Int
import kotlin.String
import kotlin.js.JsExport

@JsExport class PrestorsTalismanOfConnivery : Item() {
    override var isAutoGenerated: Boolean = false
    override var id: Int = 19377
    override var name: String = "Prestor's Talisman of Connivery"
    override var itemLevel: Int = 83
    override var quality: Int = 4
    override var icon: String = "inv_jewelry_necklace_17.jpg"
    override var inventorySlot: Int = 2
    override var itemSet: ItemSet? = null
    override var itemClass: Constants.ItemClass? = Constants.ItemClass.ARMOR
    override var itemSubclass: Constants.ItemSubclass? = Constants.ItemSubclass.MISC
    override var allowableClasses: Array<Constants.AllowableClass>? = null
    override var minDmg: Double = 0.0
    override var maxDmg: Double = 0.0
    override var speed: Double = 0.0
    override var stats: Stats = Stats(
        agility = 25,
        physicalHitRating = 10.0,
        attackPower = 22,
        rangedAttackPower = 22
      )
    override var sockets: Array<Socket> = arrayOf()
    override var socketBonus: SocketBonus? = null
    override var phase: Int = 1
}
