package data.itemscustom

import character.*
import data.Constants
import data.model.Item
import data.model.ItemSet
import data.model.Socket
import data.model.SocketBonus
import kotlin.js.JsExport

@JsExport
class TheHungeringCold : Item() {
    override var isAutoGenerated: Boolean = false

    override var id: Int = 23577
    override var name: String = "The Hungering Cold"
    override var itemLevel: Int = 89
    override var quality: Int = 4
    override var icon: String = "inv_sword_62.jpg"
    override var itemSet: ItemSet? = null
    override var inventorySlot: Int = 13
    override var itemClass: Constants.ItemClass? = Constants.ItemClass.WEAPON
    override var itemSubclass: Constants.ItemSubclass? = Constants.ItemSubclass.SWORD_1H
    override var allowableClasses: Array<Constants.AllowableClass>? = null
    override var minDmg: Double = 76.0
    override var maxDmg: Double = 143.0
    override var speed: Double = 1500.0
    override var stats: Stats = Stats(
        armor = 140,
        stamina = 14,
        expertiseRating = 14.0
    )
    override var sockets: Array<Socket> = arrayOf()
    override var socketBonus: SocketBonus? = null
    override var phase = 1
}
