package `data`.items

import `data`.Constants
import `data`.buffs.Buffs
import `data`.model.Item
import `data`.model.ItemSet
import `data`.model.Socket
import `data`.model.SocketBonus
import character.Buff
import character.Stats
import kotlin.Boolean
import kotlin.Double
import kotlin.Int
import kotlin.String
import kotlin.collections.List
import kotlin.js.JsExport
import kotlinx.serialization.Serializable

@JsExport
@Serializable
public class BladeOfUnquenchedThirst : Item() {
  public override var isAutoGenerated: Boolean = true

  public override var id: Int = 31193

  public override var name: String = "Blade of Unquenched Thirst"

  public override var itemLevel: Int = 97

  public override var quality: Int = 3

  public override var icon: String = "inv_weapon_shortblade_14.jpg"

  public override var inventorySlot: Int = 13

  public override var itemSet: ItemSet? = null

  public override var itemClass: Constants.ItemClass? = Constants.ItemClass.WEAPON

  public override var itemSubclass: Constants.ItemSubclass? = Constants.ItemSubclass.DAGGER

  public override var minDmg: Double = 53.0

  public override var maxDmg: Double = 98.0

  public override var speed: Double = 1300.0

  public override var stats: Stats = Stats(

      )

  public override var sockets: Array<Socket> = arrayOf()

  public override var socketBonus: SocketBonus? = null

  public override val buffs: List<Buff> by lazy {
        listOfNotNull(
        Buffs.byIdOrName(24585, "Drain Life", this),
        Buffs.byIdOrName(9332, "Attack Power 22", this)
        )}

}
