package `data`.items

import `data`.Constants
import `data`.model.Item
import `data`.model.ItemSet
import `data`.model.Socket
import `data`.model.SocketBonus
import character.Buff
import character.Stats
import kotlin.Array
import kotlin.Boolean
import kotlin.Double
import kotlin.Int
import kotlin.String
import kotlin.collections.List
import kotlin.js.JsExport

@JsExport
public class BristleblitzStriker : Item() {
  public override var isAutoGenerated: Boolean = true

  public override var id: Int = 30906

  public override var name: String = "Bristleblitz Striker"

  public override var itemLevel: Int = 151

  public override var quality: Int = 4

  public override var icon: String = "inv_weapon_bow_30.jpg"

  public override var inventorySlot: Int = 15

  public override var itemSet: ItemSet? = null

  public override var itemClass: Constants.ItemClass? = Constants.ItemClass.WEAPON

  public override var itemSubclass: Constants.ItemSubclass? = Constants.ItemSubclass.BOW

  public override var allowableClasses: Array<Constants.AllowableClass>? = null

  public override var minDmg: Double = 201.0

  public override var maxDmg: Double = 374.0

  public override var speed: Double = 3000.0

  public override var stats: Stats = Stats(
      stamina = 28,
      meleeCritRating = 25.0,
      rangedCritRating = 25.0
      )

  public override var sockets: Array<Socket> = arrayOf()

  public override var socketBonus: SocketBonus? = null

  public override val buffs: List<Buff> by lazy {
        listOf()}

}
