package `data`.items

import `data`.Constants
import `data`.buffs.Buffs
import `data`.model.Item
import `data`.model.ItemSet
import `data`.model.Socket
import `data`.model.SocketBonus
import character.Buff
import character.Stats
import kotlin.Array
import kotlin.Boolean
import kotlin.Double
import kotlin.Int
import kotlin.String
import kotlin.collections.List
import kotlin.js.JsExport

@JsExport
public class ChronicleOfDarkSecrets : Item() {
  public override var isAutoGenerated: Boolean = true

  public override var id: Int = 30872

  public override var name: String = "Chronicle of Dark Secrets"

  public override var itemLevel: Int = 141

  public override var quality: Int = 4

  public override var icon: String = "inv_offhand_hyjal_d_01.jpg"

  public override var inventorySlot: Int = 23

  public override var itemSet: ItemSet? = null

  public override var itemClass: Constants.ItemClass? = Constants.ItemClass.ARMOR

  public override var itemSubclass: Constants.ItemSubclass? = Constants.ItemSubclass.MISC

  public override var minDmg: Double = 0.0

  public override var maxDmg: Double = 0.0

  public override var speed: Double = 0.0

  public override var stats: Stats = Stats(
      stamina = 16,
      intellect = 12,
      spellCritRating = 23.0,
      spellHitRating = 17.0
      )

  public override var sockets: Array<Socket> = arrayOf()

  public override var socketBonus: SocketBonus? = null

  public override val buffs: List<Buff> by lazy {
        listOfNotNull(
        Buffs.byIdOrName(18058, "Increase Spell Dam 42", this)
        )}

}
