package `data`.items

import `data`.Constants
import `data`.buffs.Buffs
import `data`.model.Item
import `data`.model.ItemSet
import `data`.model.Socket
import `data`.model.SocketBonus
import character.Buff
import character.Stats
import kotlin.Boolean
import kotlin.Double
import kotlin.Int
import kotlin.String
import kotlin.collections.List

public class EterniumRunedBlade : Item() {
  public override var isAutoGenerated: Boolean = true

  public override var id: Int = 23554

  public override var name: String = "Eternium Runed Blade"

  public override var itemLevel: Int = 105

  public override var itemSet: ItemSet? = null

  public override var itemClass: Constants.ItemClass? = Constants.ItemClass.WEAPON

  public override var itemSubclass: Constants.ItemSubclass? = Constants.ItemSubclass.DAGGER

  public override var minDmg: Double = 27.600000381469727

  public override var maxDmg: Double = 113.5999984741211

  public override var speed: Double = 1700.0

  public override var stats: Stats = Stats(
      intellect = 19,
      spellCritRating = 21.0
      )

  public override var sockets: List<Socket> = listOf()

  public override var socketBonus: SocketBonus? = null

  public override val buffs: List<Buff> by lazy {
        listOfNotNull(
        Buffs.byIdOrName(37542, "Increase Spell Dam 168", this)
        )}

}
