package `data`.items

import `data`.Constants
import `data`.model.Item
import `data`.model.ItemSet
import `data`.model.Socket
import `data`.model.SocketBonus
import character.Buff
import character.Stats
import kotlin.Array
import kotlin.Boolean
import kotlin.Double
import kotlin.Int
import kotlin.String
import kotlin.collections.List
import kotlin.js.JsExport

@JsExport
public class FiremaulOfDestruction : Item() {
  public override var isAutoGenerated: Boolean = true

  public override var id: Int = 27524

  public override var name: String = "Firemaul of Destruction"

  public override var itemLevel: Int = 112

  public override var quality: Int = 3

  public override var icon: String = "inv_mace_36.jpg"

  public override var inventorySlot: Int = 17

  public override var itemSet: ItemSet? = null

  public override var itemClass: Constants.ItemClass? = Constants.ItemClass.WEAPON

  public override var itemSubclass: Constants.ItemSubclass? = Constants.ItemSubclass.MACE_2H

  public override var allowableClasses: Array<Constants.AllowableClass>? = null

  public override var minDmg: Double = 250.0

  public override var maxDmg: Double = 418.0

  public override var speed: Double = 3700.0

  public override var stats: Stats = Stats(
      strength = 31,
      stamina = 50,
      resilienceRating = 40.0
      )

  public override var sockets: Array<Socket> = arrayOf()

  public override var socketBonus: SocketBonus? = null

  public override val buffs: List<Buff> by lazy {
        listOf()}

}
