package `data`.items

import `data`.Constants
import `data`.buffs.Buffs
import `data`.model.Item
import `data`.model.ItemSet
import `data`.model.Socket
import `data`.model.SocketBonus
import character.Buff
import character.Stats
import kotlin.Boolean
import kotlin.Double
import kotlin.Int
import kotlin.String
import kotlin.collections.List

public class StaffOfPrimalFury : Item() {
  public override var isAutoGenerated: Boolean = true

  public override var id: Int = 33465

  public override var name: String = "Staff of Primal Fury"

  public override var itemLevel: Int = 132

  public override var itemSet: ItemSet? = null

  public override var itemClass: Constants.ItemClass? = Constants.ItemClass.WEAPON

  public override var itemSubclass: Constants.ItemSubclass? = Constants.ItemSubclass.STAFF

  public override var minDmg: Double = 135.10000610351562

  public override var maxDmg: Double = 285.1000061035156

  public override var speed: Double = 3000.0

  public override var stats: Stats = Stats(
      agility = 49,
      stamina = 70
      )

  public override var sockets: List<Socket> = listOf()

  public override var socketBonus: SocketBonus? = null

  public override var buffs: List<Buff> = listOfNotNull(
      Buffs.byIdOrName(44913, "Attack Power - Feral (+0973)", this),
      Buffs.byIdOrName(42109, "Armor Penetration", this)
      )
}
