package `data`.items

import `data`.Constants
import `data`.buffs.Buffs
import `data`.model.Item
import `data`.model.ItemSet
import `data`.model.Socket
import `data`.model.SocketBonus
import character.Buff
import character.Stats
import kotlin.Array
import kotlin.Boolean
import kotlin.Double
import kotlin.Int
import kotlin.String
import kotlin.collections.List
import kotlin.js.JsExport

@JsExport
public class ThoridalTheStarsFury : Item() {
  public override var isAutoGenerated: Boolean = true

  public override var id: Int = 34334

  public override var name: String = "Thori'dal, the Stars' Fury"

  public override var itemLevel: Int = 164

  public override var quality: Int = 5

  public override var icon: String = "inv_weapon_bow_39.jpg"

  public override var inventorySlot: Int = 15

  public override var itemSet: ItemSet? = null

  public override var itemClass: Constants.ItemClass? = Constants.ItemClass.WEAPON

  public override var itemSubclass: Constants.ItemSubclass? = Constants.ItemSubclass.BOW

  public override var allowableClasses: Array<Constants.AllowableClass>? = null

  public override var minDmg: Double = 355.6499938964844

  public override var maxDmg: Double = 523.6500244140625

  public override var speed: Double = 2700.0

  public override var stats: Stats = Stats(
      agility = 17,
      meleeCritRating = 16.0,
      rangedCritRating = 16.0
      )

  public override var sockets: Array<Socket> = arrayOf()

  public override var socketBonus: SocketBonus? = null

  public override val buffs: List<Buff> by lazy {
        listOfNotNull(
        Buffs.byIdOrName(15806, "Attack Power 34", this),
        Buffs.byIdOrName(43219, "Armor Penetration 112", this),
        Buffs.byIdOrName(44972, "Legendary Bow Haste", this),
        Buffs.byIdOrName(46699, "Requires No Ammo", this)
        )}

}
