package `data`.items

import `data`.Constants
import `data`.model.Item
import `data`.model.ItemSet
import `data`.model.Socket
import `data`.model.SocketBonus
import character.Buff
import character.Stats
import kotlin.Boolean
import kotlin.Double
import kotlin.Int
import kotlin.String
import kotlin.collections.List

public class BigBadWolfsPaw : Item() {
  public override var isAutoGenerated: Boolean = true

  public override var name: String = "Big Bad Wolf's Paw"

  public override var itemLevel: Int = 115

  public override var itemSet: ItemSet? = null

  public override var itemClass: Constants.ItemClass? = Constants.ItemClass.WEAPON

  public override var itemSubclass: Constants.ItemSubclass? = Constants.ItemSubclass.FIST

  public override var minDmg: Double = 153.0

  public override var maxDmg: Double = 285.0

  public override var speed: Double = 2500.0

  public override var stats: Stats = Stats(
      agility = 17,
      stamina = 18,
      physicalCritRating = 20.0,
      spellCritRating = 20.0
      )

  public override var sockets: List<Socket> = listOf()

  public override var socketBonus: SocketBonus? = null

  public override var buffs: List<Buff> = listOf()
}
