package `data`.items

import `data`.Constants
import `data`.buffs.Buffs
import `data`.model.Color
import `data`.model.Item
import `data`.model.ItemSet
import `data`.model.Socket
import `data`.model.SocketBonus
import `data`.socketbonus.SocketBonuses
import character.Buff
import character.Stats
import kotlin.Boolean
import kotlin.Double
import kotlin.Int
import kotlin.String
import kotlin.collections.List

public class BladeOfLifesInevitability : Item() {
  public override var isAutoGenerated: Boolean = true

  public override var name: String = "Blade of Life's Inevitability"

  public override var itemLevel: Int = 154

  public override var itemSet: ItemSet? = null

  public override var itemClass: Constants.ItemClass? = Constants.ItemClass.WEAPON

  public override var itemSubclass: Constants.ItemSubclass? = Constants.ItemSubclass.THROWN

  public override var minDmg: Double = 155.0

  public override var maxDmg: Double = 233.0

  public override var speed: Double = 2000.0

  public override var stats: Stats = Stats(
      stamina = 19,
      physicalHasteRating = 16.0,
      spellHasteRating = 16.0
      )

  public override var sockets: List<Socket> = listOf(
      Socket(Color.YELLOW)
      )

  public override var socketBonus: SocketBonus? = SocketBonuses.byId(3114)

  public override var buffs: List<Buff> = listOfNotNull(
      Buffs.byIdOrName(14089, "Attack Power 36", this)
      )
}
