package `data`.items

import `data`.Constants
import `data`.buffs.Buffs
import `data`.itemsets.ItemSets
import `data`.model.Color
import `data`.model.Item
import `data`.model.ItemSet
import `data`.model.Socket
import `data`.model.SocketBonus
import `data`.socketbonus.SocketBonuses
import character.Buff
import character.Stats
import kotlin.Boolean
import kotlin.Double
import kotlin.Int
import kotlin.String
import kotlin.collections.List

public class BracersOfTheTempest : Item() {
  public override var isAutoGenerated: Boolean = true

  public override var name: String = "Bracers of the Tempest"

  public override var itemLevel: Int = 154

  public override var itemSet: ItemSet? = ItemSets.byId(671)

  public override var itemClass: Constants.ItemClass? = Constants.ItemClass.ARMOR

  public override var itemSubclass: Constants.ItemSubclass? = Constants.ItemSubclass.CLOTH

  public override var minDmg: Double = 0.0

  public override var maxDmg: Double = 0.0

  public override var speed: Double = 0.0

  public override var stats: Stats = Stats(
      stamina = 18,
      intellect = 17,
      spirit = 14,
      spellCritRating = 11.0,
      spellHasteRating = 26.0
      )

  public override var sockets: List<Socket> = listOf(
      Socket(Color.RED)
      )

  public override var socketBonus: SocketBonus? = SocketBonuses.byId(3152)

  public override var buffs: List<Buff> = listOfNotNull(
      Buffs.byId(18055)
      )
}
