package `data`.items

import `data`.Constants
import `data`.model.Item
import `data`.model.ItemSet
import `data`.model.Socket
import `data`.model.SocketBonus
import character.Buff
import character.Stats
import kotlin.Boolean
import kotlin.Double
import kotlin.Int
import kotlin.String
import kotlin.collections.List

public class Gorehowl : Item() {
  public override var isAutoGenerated: Boolean = true

  public override var name: String = "Gorehowl"

  public override var itemLevel: Int = 125

  public override var itemSet: ItemSet? = null

  public override var itemClass: Constants.ItemClass? = Constants.ItemClass.WEAPON

  public override var itemSubclass: Constants.ItemSubclass? = Constants.ItemSubclass.AXE_2H

  public override var minDmg: Double = 345.0

  public override var maxDmg: Double = 518.0

  public override var speed: Double = 3600.0

  public override var stats: Stats = Stats(
      strength = 49,
      agility = 43,
      stamina = 51
      )

  public override var sockets: List<Socket> = listOf()

  public override var socketBonus: SocketBonus? = null

  public override var buffs: List<Buff> = listOf()
}
