package `data`.items

import `data`.Constants
import `data`.buffs.Buffs
import `data`.itemsets.ItemSets
import `data`.model.Color
import `data`.model.Item
import `data`.model.ItemSet
import `data`.model.Socket
import `data`.model.SocketBonus
import `data`.socketbonus.SocketBonuses
import character.Buff
import character.Stats
import kotlin.Boolean
import kotlin.Double
import kotlin.Int
import kotlin.String
import kotlin.collections.List

public class GronnstalkersBracers : Item() {
  public override var isAutoGenerated: Boolean = true

  public override var name: String = "Gronnstalker's Bracers"

  public override var itemLevel: Int = 154

  public override var itemSet: ItemSet? = ItemSets.byId(669)

  public override var itemClass: Constants.ItemClass? = Constants.ItemClass.ARMOR

  public override var itemSubclass: Constants.ItemSubclass? = Constants.ItemSubclass.MAIL

  public override var minDmg: Double = 0.0

  public override var maxDmg: Double = 0.0

  public override var speed: Double = 0.0

  public override var stats: Stats = Stats(
      agility = 23,
      stamina = 16,
      intellect = 16,
      physicalCritRating = 17.0
      )

  public override var sockets: List<Socket> = listOf(
      Socket(Color.RED)
      )

  public override var socketBonus: SocketBonus? = SocketBonuses.byId(3149)

  public override var buffs: List<Buff> = listOfNotNull(
      Buffs.byIdOrName(15817, "Attack Power 64", this),
      Buffs.byIdOrName(43219, "Armor Penetration 112", this)
      )
}
