package `data`.items

import `data`.Constants
import `data`.buffs.Buffs
import `data`.model.Item
import `data`.model.ItemSet
import `data`.model.Socket
import `data`.model.SocketBonus
import character.Buff
import character.Stats
import kotlin.Boolean
import kotlin.Double
import kotlin.Int
import kotlin.String
import kotlin.collections.List

public class KhoriumChampion : Item() {
  public override var isAutoGenerated: Boolean = true

  public override var id: Int = 23541

  public override var name: String = "Khorium Champion"

  public override var itemLevel: Int = 105

  public override var itemSet: ItemSet? = null

  public override var itemClass: Constants.ItemClass? = Constants.ItemClass.WEAPON

  public override var itemSubclass: Constants.ItemSubclass? = Constants.ItemSubclass.SWORD_2H

  public override var minDmg: Double = 286.0

  public override var maxDmg: Double = 430.0

  public override var speed: Double = 3300.0

  public override var stats: Stats = Stats(
      strength = 50,
      physicalHitRating = 37.0
      )

  public override var sockets: List<Socket> = listOf()

  public override var socketBonus: SocketBonus? = null

  public override var buffs: List<Buff> = listOfNotNull(
      Buffs.byIdOrName(16916, "Strength of the Champion", this)
      )
}
