package `data`.items

import `data`.Constants
import `data`.buffs.Buffs
import `data`.model.Item
import `data`.model.ItemSet
import `data`.model.Socket
import `data`.model.SocketBonus
import character.Buff
import character.Stats
import kotlin.Boolean
import kotlin.Double
import kotlin.Int
import kotlin.String
import kotlin.collections.List

public class MogorsAnointingClub : Item() {
  public override var isAutoGenerated: Boolean = true

  public override var name: String = "Mogor's Anointing Club"

  public override var itemLevel: Int = 103

  public override var itemSet: ItemSet? = null

  public override var itemClass: Constants.ItemClass? = Constants.ItemClass.WEAPON

  public override var itemSubclass: Constants.ItemSubclass? = Constants.ItemSubclass.MACE_1H

  public override var minDmg: Double = 47.27000045776367

  public override var maxDmg: Double = 126.2699966430664

  public override var speed: Double = 2100.0

  public override var stats: Stats = Stats(
      stamina = 19,
      intellect = 13
      )

  public override var sockets: List<Socket> = listOf()

  public override var socketBonus: SocketBonus? = null

  public override var buffs: List<Buff> = listOfNotNull(
      Buffs.byId(21620),
      Buffs.byId(33328)
      )
}
