package `data`.items

import `data`.Constants
import `data`.model.Item
import `data`.model.ItemSet
import `data`.model.Socket
import `data`.model.SocketBonus
import character.Buff
import character.Stats
import kotlin.Boolean
import kotlin.Double
import kotlin.Int
import kotlin.String
import kotlin.collections.List

public class ScepterOfShatar : Item() {
  public override var isAutoGenerated: Boolean = true

  public override var name: String = "Scepter of Sha'tar"

  public override var itemLevel: Int = 115

  public override var itemSet: ItemSet? = null

  public override var itemClass: Constants.ItemClass? = Constants.ItemClass.WEAPON

  public override var itemSubclass: Constants.ItemSubclass? = Constants.ItemSubclass.MACE_2H

  public override var minDmg: Double = 245.0

  public override var maxDmg: Double = 408.0

  public override var speed: Double = 3500.0

  public override var stats: Stats = Stats(
      strength = 31,
      stamina = 28,
      intellect = 26,
      physicalCritRating = 30.0
      )

  public override var sockets: List<Socket> = listOf()

  public override var socketBonus: SocketBonus? = null

  public override var buffs: List<Buff> = listOf()
}
