package `data`.items

import `data`.Constants
import `data`.buffs.Buffs
import `data`.model.Item
import `data`.model.ItemSet
import `data`.model.Socket
import `data`.model.SocketBonus
import character.Buff
import character.Stats
import kotlin.Boolean
import kotlin.Double
import kotlin.Int
import kotlin.String
import kotlin.collections.List

public class ShardOfTheVirtuous : Item() {
  public override var isAutoGenerated: Boolean = true

  public override var id: Int = 28522

  public override var name: String = "Shard of the Virtuous"

  public override var itemLevel: Int = 115

  public override var itemSet: ItemSet? = null

  public override var itemClass: Constants.ItemClass? = Constants.ItemClass.WEAPON

  public override var itemSubclass: Constants.ItemSubclass? = Constants.ItemSubclass.MACE_1H

  public override var minDmg: Double = 28.030000686645508

  public override var maxDmg: Double = 129.02999877929688

  public override var speed: Double = 1900.0

  public override var stats: Stats = Stats(
      stamina = 22,
      intellect = 20
      )

  public override var sockets: List<Socket> = listOf()

  public override var socketBonus: SocketBonus? = null

  public override var buffs: List<Buff> = listOfNotNull(
      Buffs.byIdOrName(40107, "Increase Healing 348", this),
      Buffs.byIdOrName(21627, "Increased Mana Regen", this)
      )
}
