package `data`.items

import `data`.Constants
import `data`.buffs.Buffs
import `data`.model.Item
import `data`.model.ItemSet
import `data`.model.Socket
import `data`.model.SocketBonus
import character.Buff
import character.Stats
import kotlin.Boolean
import kotlin.Double
import kotlin.Int
import kotlin.String
import kotlin.collections.List

public class StanchionOfPrimalInstinct : Item() {
  public override var isAutoGenerated: Boolean = true

  public override var name: String = "Stanchion of Primal Instinct"

  public override var itemLevel: Int = 154

  public override var itemSet: ItemSet? = null

  public override var itemClass: Constants.ItemClass? = Constants.ItemClass.WEAPON

  public override var itemSubclass: Constants.ItemSubclass? = Constants.ItemSubclass.STAFF

  public override var minDmg: Double = 136.5

  public override var maxDmg: Double = 305.5

  public override var speed: Double = 3000.0

  public override var stats: Stats = Stats(
      strength = 47,
      agility = 75,
      stamina = 50
      )

  public override var sockets: List<Socket> = listOf()

  public override var socketBonus: SocketBonus? = null

  public override var buffs: List<Buff> = listOfNotNull(
      Buffs.byIdOrName(45783, "Attack Power - Feral (+1197)", this),
      Buffs.byIdOrName(42157, "Armor Penetration 350", this)
      )
}
