package `data`.items

import `data`.Constants
import `data`.buffs.Buffs
import `data`.model.Item
import `data`.model.ItemSet
import `data`.model.Socket
import `data`.model.SocketBonus
import character.Buff
import character.Stats
import kotlin.Boolean
import kotlin.Double
import kotlin.Int
import kotlin.String
import kotlin.collections.List

public class TalonOfThePhoenix : Item() {
  public override var isAutoGenerated: Boolean = true

  public override var name: String = "Talon of the Phoenix"

  public override var itemLevel: Int = 134

  public override var itemSet: ItemSet? = null

  public override var itemClass: Constants.ItemClass? = Constants.ItemClass.WEAPON

  public override var itemSubclass: Constants.ItemSubclass? = Constants.ItemSubclass.FIST

  public override var minDmg: Double = 182.0

  public override var maxDmg: Double = 339.0

  public override var speed: Double = 2700.0

  public override var stats: Stats = Stats(
      physicalCritRating = 19.0,
      physicalHitRating = 15.0,
      spellCritRating = 19.0,
      spellHitRating = 15.0
      )

  public override var sockets: List<Socket> = listOf()

  public override var socketBonus: SocketBonus? = null

  public override var buffs: List<Buff> = listOfNotNull(
      Buffs.byId(15812)
      )
}
