package `data`.items

import `data`.Constants
import `data`.model.Item
import `data`.model.ItemSet
import `data`.model.Socket
import `data`.model.SocketBonus
import character.Buff
import character.Stats
import kotlin.Boolean
import kotlin.Double
import kotlin.Int
import kotlin.String
import kotlin.collections.List

public class TridentOfTheOutcastTribe : Item() {
  public override var isAutoGenerated: Boolean = true

  public override var name: String = "Trident of the Outcast Tribe"

  public override var itemLevel: Int = 100

  public override var itemSet: ItemSet? = null

  public override var itemClass: Constants.ItemClass? = Constants.ItemClass.WEAPON

  public override var itemSubclass: Constants.ItemSubclass? = Constants.ItemSubclass.POLEARM

  public override var minDmg: Double = 270.0

  public override var maxDmg: Double = 406.0

  public override var speed: Double = 3200.0

  public override var stats: Stats = Stats(
      strength = 37,
      stamina = 54,
      physicalHitRating = 36.0
      )

  public override var sockets: List<Socket> = listOf()

  public override var socketBonus: SocketBonus? = null

  public override var buffs: List<Buff> = listOf()
}
