package `data`.items

import `data`.Constants
import `data`.buffs.Buffs
import `data`.model.Color
import `data`.model.Item
import `data`.model.ItemSet
import `data`.model.Socket
import `data`.model.SocketBonus
import `data`.socketbonus.SocketBonuses
import character.Buff
import character.Stats
import kotlin.Boolean
import kotlin.Double
import kotlin.Int
import kotlin.String
import kotlin.collections.List

public class TwinbladeOfThePhoenix : Item() {
  public override var isAutoGenerated: Boolean = true

  public override var id: Int = 29993

  public override var name: String = "Twinblade of the Phoenix"

  public override var itemLevel: Int = 141

  public override var itemSet: ItemSet? = null

  public override var itemClass: Constants.ItemClass? = Constants.ItemClass.WEAPON

  public override var itemSubclass: Constants.ItemSubclass? = Constants.ItemSubclass.SWORD_2H

  public override var minDmg: Double = 375.0

  public override var maxDmg: Double = 564.0

  public override var speed: Double = 3600.0

  public override var stats: Stats = Stats(
      stamina = 53,
      physicalCritRating = 37.0
      )

  public override var sockets: List<Socket> = listOf(
      Socket(Color.RED),
      Socket(Color.YELLOW),
      Socket(Color.BLUE)
      )

  public override var socketBonus: SocketBonus? = SocketBonuses.byId(2936)

  public override var buffs: List<Buff> = listOfNotNull(
      Buffs.byIdOrName(34751, "Attack Power 110", this)
      )
}
