package `data`.items

import `data`.Constants
import `data`.buffs.Buffs
import `data`.model.Item
import `data`.model.ItemSet
import `data`.model.Socket
import `data`.model.SocketBonus
import character.Buff
import character.Stats
import kotlin.Boolean
import kotlin.Double
import kotlin.Int
import kotlin.String
import kotlin.collections.List

public class WandOfTheSeer : Item() {
  public override var isAutoGenerated: Boolean = true

  public override var id: Int = 30859

  public override var name: String = "Wand of the Seer"

  public override var itemLevel: Int = 109

  public override var itemSet: ItemSet? = null

  public override var itemClass: Constants.ItemClass? = Constants.ItemClass.WEAPON

  public override var itemSubclass: Constants.ItemSubclass? = Constants.ItemSubclass.WAND

  public override var minDmg: Double = 110.0

  public override var maxDmg: Double = 205.0

  public override var speed: Double = 1300.0

  public override var stats: Stats = Stats(
      intellect = 8,
      spirit = 5
      )

  public override var sockets: List<Socket> = listOf()

  public override var socketBonus: SocketBonus? = null

  public override var buffs: List<Buff> = listOfNotNull(
      Buffs.byIdOrName(9346, "Increase Spell Dam 18", this)
      )
}
